services:

  postgres:
    image: postgres:16.5
    container_name: postgres-1
    hostname: postgres-1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data

volumes:
  postgres:
    name: invoice-ocr-postgres
    external: true
